languageCode: en-us
baseURL: "https://rahulogoel.github.io"
title: Rahul Goel
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Rahul Goel
  description: "I like to go beyond the surface and explore the depths of deep neural nets"
  keywords: [Blog, Portfolio, Data Science, Machine Learning, Deep Learning, Artificial Intelligence (AI)]
  # author: Rahul Goel
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Home"
    icon: "images/coding.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Welcome! \U0001F44B I'm Rahul Goel"
    subtitle: "I like to go beyond the surface and explore the depths of deep neural nets"
    # imageUrl: "images/test.png"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: "temp"
    # buttons:
    #   - name: About
    #     url: about
    #   - name: Blogs
    #     url: blogs
      # - name: Projects
      #   url: projects

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B I'm Rahul Goel"
    Content: "I like to go beyond the surface and explore the depths of deep neural nets"

  socialIcons:
    - name: x
      url: "https://x.com/rahulogoel"
    - name: github
      url: "https://github.com/rahulogoel"
    - name: linkedin
      url: "https://www.linkedin.com/in/rahulogoel"
    - name: email
      url: "mailto:me.rahulgoel@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: blog
      name: Blog
      url: /blogs/
      weight: 2
    # - identifier: projects
    #   name: Projects
    #   url: /projects/
    #   weight: 2
    # - identifier: infographics
    #   name: Infographics
    #   url: /infographics/
    #   weight: 3
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai